export default {
  TOPIC: {
    SET_TOPIC: 'SET_TOPIC',
    LOADING: 'LOADING_DATA_TOPIC',
    SET_DATA_TOPIC: 'SET_DATA_TOPIC',
    SET_TOPIC_PAGE: 'SET_TOPIC_PAGE',
    SET_GET_DATA: 'SET_GET_DATA',
    SET_SHOW_DETAILS: 'SET_SHOW_DETAILS',
    SET_DATA_DETAILS: 'SET_DATA_DETAILS',
    SET_LOADING_DETAILS: 'SET_LOADING_DETAILS',
  },
  SEARCH: {
    SET_SEARCH: 'SET_SEARCH',
  },
  MODALS: {
    TOGGLE: 'SET_SHOW_MODAL',
  },
};
